services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: meditherakis
      POSTGRES_PASSWORD: pa55word
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
